/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.narh.sample;

import org.springframework.context.support.ClassPathXmlApplicationContext;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String ...arhs) throws Exception {
    	ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("application-context.xml");
    	Test1Exec exec = (Test1Exec) context.getBean(Test1Exec.class);
    	exec.exec();
        context.close();
    }
}
