/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.narh.sample;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.context.support.PropertySourcesPlaceholderConfigurer;

@Configuration
@PropertySource(value = {"classpath:test2.properties"})
public class App2 {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String ...arhs) throws Exception {
    	ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("application-context.xml");
    	Test2Bean bean = (Test2Bean) context.getBean(Test2Bean.class);
        System.out.println(bean.toString());
        context.close();
    }

	@Bean
    public static PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer() {
        return new PropertySourcesPlaceholderConfigurer();
    }
}
