/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.narh.sample;

import java.util.function.BiConsumer;
import java.util.function.Consumer;

import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.github.narh.sample.exec.AppExec;

public class App2 {

  public static void main(String... args) throws Exception {
    ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("application-context.xml");

    ((AppExec) context.getBean("test2Exec")).exec();

    context.close();
  }

  public static  <T> Consumer<T> Try(ThrowableConsumer<T> onTry, BiConsumer<Exception, T> onCatch) {
    return x -> {
      try {
        onTry.accept(x);
      }
      catch (Exception t) {
        onCatch.accept(t, x);
      }
    };
  }
}
