/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.narh.sample;

import org.springframework.context.annotation.Bean;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.context.support.PropertySourcesPlaceholderConfigurer;

public class App2 {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String ...arhs) throws Exception {
    	ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("application-context.xml");
    	Test2Exec exec = (Test2Exec) context.getBean(Test2Exec.class);
    	exec.exec();
        context.close();
    }
}
